#include <cuda_runtime.h>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <vector>
#include <algorithm>
#define CUDA_OK(x) do { cudaError_t e=(x); if(e!=cudaSuccess){std::fprintf(stderr,"CUDA error %s:%d code=%d name=%s description=%s\n",__FILE__,__LINE__,(int)e,cudaGetErrorName(e),cudaGetErrorString(e)); return 2;} } while(0)
template<int TILE> __global__ void tiled_attention(const float* q,const float* k,const float* v,float* out,int B,int H,int T,int D){
  extern __shared__ float smem[]; float* sk=smem; float* sv=smem+TILE*D; int row=blockIdx.x,total=B*H*T;if(row>=total)return;int d=threadIdx.x;if(d>=D)return;int t=row%T,bh=row/T;float m=-INFINITY,l=0,acc=0,scale=rsqrtf((float)D);int qb=(bh*T+t)*D;
  for(int start=0;start<=t;start+=TILE){int width=min(TILE,t-start+1);for(int x=d;x<width*D;x+=blockDim.x){int j=x/D,c=x%D;int src=(bh*T+start+j)*D+c;sk[j*D+c]=k[src];sv[j*D+c]=v[src];}__syncthreads();for(int j=0;j<width;j++){float score=0;for(int c=0;c<D;c++)score+=q[qb+c]*sk[j*D+c];score*=scale;float next=fmaxf(m,score),old=isinf(m)?0:expf(m-next),p=expf(score-next);acc=old*acc+p*sv[j*D+d];l=old*l+p;m=next;}__syncthreads();}out[qb+d]=acc/l;
}
int main(int argc,char**argv){int T=argc>1?std::atoi(argv[1]):128,B=1,H=2,D=32;size_t n=(size_t)B*H*T*D;std::vector<float>q(n),k(n),v(n);for(size_t i=0;i<n;i++){q[i]=std::sin(i*.017f);k[i]=std::cos(i*.013f);v[i]=std::sin(i*.009f);}float*dq,*dk,*dv,*do_;CUDA_OK(cudaMalloc(&dq,n*4));CUDA_OK(cudaMalloc(&dk,n*4));CUDA_OK(cudaMalloc(&dv,n*4));CUDA_OK(cudaMalloc(&do_,n*4));CUDA_OK(cudaMemcpy(dq,q.data(),n*4,cudaMemcpyHostToDevice));CUDA_OK(cudaMemcpy(dk,k.data(),n*4,cudaMemcpyHostToDevice));CUDA_OK(cudaMemcpy(dv,v.data(),n*4,cudaMemcpyHostToDevice));int blocks=B*H*T,threads=std::max(D,128);size_t shared=2*(size_t)32*D*sizeof(float);tiled_attention<32><<<blocks,threads,shared>>>(dq,dk,dv,do_,B,H,T,D);CUDA_OK(cudaGetLastError());CUDA_OK(cudaDeviceSynchronize());cudaEvent_t a,z;CUDA_OK(cudaEventCreate(&a));CUDA_OK(cudaEventCreate(&z));for(int i=0;i<10;i++)tiled_attention<32><<<blocks,threads,shared>>>(dq,dk,dv,do_,B,H,T,D);CUDA_OK(cudaDeviceSynchronize());CUDA_OK(cudaEventRecord(a));for(int i=0;i<50;i++)tiled_attention<32><<<blocks,threads,shared>>>(dq,dk,dv,do_,B,H,T,D);CUDA_OK(cudaEventRecord(z));CUDA_OK(cudaEventSynchronize(z));float ms;CUDA_OK(cudaEventElapsedTime(&ms,a,z));std::printf("{\"context\":%d,\"median_like_ms\":%.6f,\"launches\":50,\"kernel\":\"shared_memory_tiled_reference\",\"shared_bytes\":%zu}\n",T,ms/50,shared);return 0;}
